### LOGIN
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "asd",
    "password": "asd"
}
### REGISTER
POST http://localhost:5000/register
Content-Type: application/json

{
    "email": "test@email.com",
    "username": "asd",
    "password": "asd",
    "role": "asd"
}

### REGISTER ADMIN
POST http://localhost:5000/users/registerAdmin
Content-Type: application/json

{
    "email": "admin@admin.com",
    "username": "admin",
    "password": "admin",
    "role": "admin"
}
### GET USERS
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhdmlkIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgyMDg3NTYyLCJleHAiOjE2ODIwODc1NzJ9.yZFcHDgJ6vbwetACQUo_-w94uC7ksn8RfYS3wIJG58k

### post Time 
POST http://localhost:5000/bookings/postAvailableTime
Content-Type: application/json

{
    "service_id": "64492f7eb34eac18c1c5626a",
    "startTime": "2002-02-02",
    "endTime": "2002-02-02"
}

###
GET http://localhost:5000/bookings/getAvailableTimeSlots/644c378a049948fffb0a19d7/2023-05-23T09:00:00.000Z
Content-Type: application/json

### 
POST http://localhost:5000/bookings/postService
Content-Type: application/json

###
GET http://localhost:5000/employees/getEmployees/644a83d1f0a732d4a429ab87,644a83d1f0a732d4a429ab88
Content-Type: application/json

### GET ALL THE USERS
GET http://localhost:5000/admin/getUsers
Content-Type: application/json


### ADD A NEW USER FROM THE ADMIN ROUTES
POST http://localhost:5000/admin/addUser
Content-Type: application/json

{
    "username": "hej",
    "email": "hej@gmail.com",
    "phoneNumber" : "+4668656656",
    "password": "hejhej"
}

### UPDATE USER BY ID
PUT http://localhost:5000/admin/updateUser
Content-Type: application/json

{
    "id": "644faace1687a1953d050732",
    "username": "hej1",
    "email": "hej1@gmail.com",
    "phoneNumber" : "+466865665611",
    "password": "hejhej1"
}

### REMOVE USER BY ID
DELETE http://localhost:5000/admin/removeUser
Content-Type: application/json

{
    "id": "644faace1687a1953d050732"
}

### 
GET http://localhost:5000/bookings/getAmount
Content-Type: application/json