### LOGIN
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}
### REGISTER
POST http://localhost:5000/register
Content-Type: application/json

{
    "email": "test@email.com",
    "name": "asd",
    "password": "asd",
    "role": "asd"
}
### GET USERS
GET http://localhost:5000/getUserData
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJyb2xlIjoidXNlciIsImlhdCI6MTY4MjQzMzc5M30.OyDbEINTU9JilR43EkgAOKkrIpKgYQWxsp7cy1NBc78
